<div class="clearer"></div>
<div id="footer"><!-- Start Footer -->
	<p>Site by WD6AWP. <a href="http://www.youtube.com/watch?v=aZJZK6rzjns" target="_blank">There are some who call me&hellip; Tim?</a></p>
</div><!-- End Footer -->
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>